apiVersion: v1
kind: Service
metadata:
  name: devops-site-service
  namespace: devops-site
spec:
  type: NodePort
  selector:
    app: devops-site
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30010  <-- REMOVE this line

